### PR TITLE
WIP: Docs(Enterprise): Notify that Offline restore feature is deprecated

### PR DESCRIPTION
**Pull request by kevinmingtarja**
Description:

@rarvikar mentioned that the offline restore feature is deprecated (`v21.03.0` was the last version to have it), but it is not stated in the docs, which might confuse readers. So, I think we should do something to notify of this change.

cc: @meghalims @MichelDiz

### CODE REVIEW

**Comment by MichelDiz** [comment]
@kevinmingtarja is this Eligible for v22.0.0? or you wanna add this to master/main? And later cherry pick it to v22.0.0.

**Comment by kevinmingtarja** [comment]
@MichelDiz I think we can add this to master first, then later cherry pick it.

cc: @meghalims

**Comment by MichelDiz** [comment]
PS. @kevinmingtarja now everything new needs to go to Main branch.

**Comment by kevinmingtarja** [comment]
Okay I'm recreating this PR.

**Pull request closed without merging**
