### PR TITLE
Docs(GraphQL): Say that spaces aren't the only delimiter for anyofterms

### PR DESCRIPTION
**Pull request by catherineluse**
Source: https://discuss.dgraph.io/t/cant-fully-delete-an-edge-between-nodes/15090/4

### CODE REVIEW

**Comment by MichelDiz** [comment]
Can you sign the CLA?

**Comment by catherineluse** [comment]
I have signed it

**Comment by MichelDiz** [comment]
Hey @catherineluse thank you for your contribution. But feels a bit odd your tittle.

You say "Docs(GraphQL):" but your edits are in the DQL part. I gonna approve, but pay attention next time. These tags in the title are for us to pre-filter the content by speeding up or decreasing the priority of the review.

**Review by MichelDiz — APPROVED** [review]

**Comment by MichelDiz** [comment]
@skrdgraph Help me out with this. She is PR against v21.03, Shouldn't be master? Maybe commit to this release and also to master.

**Comment by catherineluse** [comment]
The reason I marked it as GraphQL is because I was a GraphQL user, reading the docs for the auto-generated GraphQL API. I don't know anything about DQL. I made the doc update because I was getting weird, counterintuitive results when using the GraphQL API and had to go to the forums to figure out the reason why.

**Comment by catherineluse** [comment]
Closing because this PR is cluttering up my GitHub UI. Too bad the next person will have to suffer through the same problem that I did.

**Pull request closed without merging**
