### PR TITLE
Corrrect of defining a Type in GraphQL Response

### PR DESCRIPTION
**Pull request by pshaddel**

### CODE REVIEW

**Comment by MichelDiz** [comment]
This PR looks wrong. Can you clarify the change?

**Comment by pshaddel** [comment]
> This PR looks wrong. Can you clarify the change?

The type in document is not a valid Typescript type. In Typescript you need an equal to declare a type.

**Review by MichelDiz — APPROVED** [review]

**Comment by MichelDiz** [comment]
Can you sign the CLA?

**Comment by pshaddel** [comment]
> Can you sign the CLA?

It is singed now.

**Comment by MichelDiz** [comment]
I think this is wrong. The docs isn't about TypeScript Types. It is about GraphQL.

**Pull request merged**
